apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: codegen-110204-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/codegen-110204/overlays/development
    repoURL: https://github.com/fpetk/codegen-110204-gitops.git
    targetRevision: main
  destination:
    namespace: ai-software-templates-dev
    server: https://api.qrc25-neetj-mhu.i6rg.p3.openshiftapps.com:443
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: ai-rhdh
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
