apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: codegen-110204
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: codegen-110204
  name: codegen-110204
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: codegen-110204
    weight: 100
  wildcardPolicy: None
