apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen-110204
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tpetkos/codegen-110204:c5303dd85cebb75b6ab73f853fb5c64a4709bb2c@sha256:daa4f6e8121dbe68b5dc02c6b06c700851f93fc8979f5615dc1aabf6f3629e0b # use pre-built to bootstrap
          name: app-inference
